version: "3.0"
services:
    app:
      build:
          context: ./app
          args:
              - MOLGENIS_VERSION=5.3.0-SNAPSHOT
      ports:
        - "8081:8080"
      links:
        - db
        - elasticsearch
      volumes:
        - app-data:/opt/molgenis
      depends_on:
        - elasticsearch
        - graphdb
        - db
        - opencpu
    db:
      image: postgres:9.6-alpine
      environment:
          - POSTGRES_USER=molgenis
          - POSTGRES_PASSWORD=molgenis
          - POSTGRES_DB=molgenis
      expose:
        - "5432"
      volumes:
        - db-data:/var/lib/postgresql/data
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.4.1
        container_name: elasticsearch
        environment:
          - cluster.name=molgenis
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - xpack.security.enabled=false
        ulimits:
          memlock:
            soft: -1
            hard: -1
        volumes:
          - es-data:/usr/share/elasticsearch/data
        ports:
          - 9200:9200
          - 9300:9300
    opencpu:
        build:
          context: ./opencpu
        ports:
          - 8004:8004
    graphdb:
        image: ontotext/graphdb:8.3.1-free
        ports:
            - "7200:7200"
volumes:
    db-data:
    app-data:
    es-data:
        driver: local

